## [Ломать — не строить](../../../solutions/5.3/53_b.py)

Давайте немного поиграем в «багоюзеров».

Вашему решению будет предоставлена функция `func`, которая принимает два позиционных параметра и производит с ними некую __математическую__ операцию.

Предложите вызов функции, который гарантированно породит ошибку внутри функции.

### Примечание

Если ошибка произойдёт внутри функции, то она будет перехвачена и обработана.\
Если же она произойдет в вашем коде, то программа будет завершена с ошибкой.

### Пример 1

**Ввод**
```python
def func(a, b):
    return a + b
```

**Вывод**
```plaintext
Ура! Ошибка!
```

### Пример 2

**Ввод**
```python
def func(a, b):
    return a * b
```

**Вывод**
```plaintext
Ура! Ошибка!
```